experiment:
    max_trials: 20
    algorithms:
        tpe:
            seed: null
            n_initial_points: 12
            n_ei_candidates: 8
            gamma: 0.25
            equal_weight: False
            prior_weight: 1.0
            full_weight_num: 25

worker:
    max_trials: 1

storage:
    database:
        type: 'mongodb'
        name: 'orion_fundus'
        host: 'mongodb://localhost'
        port: 27017

evc:
    ignore_code_changes: True